-- ============================================================
-- Afams Ltd — Normalize order line items into a separate table
-- Migration: 010_order_items_table.sql
--
-- Creates order_items (one row per product per order) so that
-- multi-item orders are stored correctly.  The webhook writes
-- here after every successful Paystack charge.
--
-- The legacy orders.items JSONB column is left in place for
-- backward compatibility with orders placed before this
-- migration.
-- ============================================================

-- ── Table ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.order_items (
  id           uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id     uuid          NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id   text          NOT NULL,
  product_name text          NOT NULL,
  quantity     int           NOT NULL CHECK (quantity > 0),
  unit_price   numeric(10,2) NOT NULL CHECK (unit_price >= 0),
  subtotal     numeric(10,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
  created_at   timestamptz   NOT NULL DEFAULT now()
);

-- ── Row Level Security ────────────────────────────────────────
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Authenticated (admin) users can read and write order_items
DROP POLICY IF EXISTS "order_items_admin_select" ON public.order_items;
CREATE POLICY "order_items_admin_select" ON public.order_items
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "order_items_admin_insert" ON public.order_items;
CREATE POLICY "order_items_admin_insert" ON public.order_items
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "order_items_admin_update" ON public.order_items;
CREATE POLICY "order_items_admin_update" ON public.order_items
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Anon SELECT: required by the order-confirm.html receipt page.
-- The paystack_ref in the URL acts as a capability token —
-- it is a random string generated by Paystack and is not
-- guessable.  This is standard practice for "view your receipt"
-- pages.  Replace with an Edge Function proxy if stricter
-- access control is needed.
DROP POLICY IF EXISTS "order_items_anon_select" ON public.order_items;
CREATE POLICY "order_items_anon_select" ON public.order_items
  FOR SELECT TO anon USING (true);

-- Also allow anon SELECT on orders so the receipt page can
-- look up the parent order row by paystack_ref.
DROP POLICY IF EXISTS "orders_anon_select" ON public.orders;
CREATE POLICY "orders_anon_select" ON public.orders
  FOR SELECT TO anon USING (true);

-- ── Indexes ───────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS order_items_order_id_idx   ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS order_items_product_id_idx ON public.order_items(product_id);
